name: docker build & publish
on: 
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        name: version and build
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            id-token: write
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false

            #### ONLY RUN IF NOT MASTER ####
            # Initialize and configure Docker Buildx, a modern building toolkit.
            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v3
              # Authenticate against the specified container registry, but skip this during pull requests.
            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

           
            # Generate metadata like tags and labels for the Docker image.
            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


            # Push the image to the registry, excluding push during pull requests.
            - name: Push docker image
              id: push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  tags: latest
                  labels: ${{ steps.meta.outputs.labels }}
