name: docker build & publish
on: 
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        name: version and build
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            id-token: write
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false

            #### ONLY RUN IF NOT MASTER ####
            # Initialize and configure Docker Buildx, a modern building toolkit.
            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

              # Authenticate against the specified container registry, but skip this during pull requests.
            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

           
            # Generate metadata like tags and labels for the Docker image.
            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            # Create the Docker image and 
            - name: Build Docker image
              id: build
              uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
              with:
                  context: .
                  load: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            # Push the image to the registry, excluding push during pull requests.
            - name: Push docker image
              id: push
              uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
              with:
                  context: .
                  push: ${{ github.ref_name == 'master' }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
